# Generated by Django 4.0.1 on 2022-02-01 12:20

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                error_messages={"unique": "A company with that name already exists."},
                max_length=128,
                unique=True,
                verbose_name="Name of company",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Username already exists."},
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="Company username for authorization",
            ),
        ),
    ]
